sudo: required
language: rust

# Cache cargo symbols for faster build
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build --verbose --release
  - cargo test --verbose --release
  - cargo test --verbose --release -- --ignored
