[package]
name = "ire"
description = "I2P router implementation in Rust"
version = "0.0.1"
license = "MIT"
authors = ["Jack Grigg <str4d@i2pmail.org>"]
homepage = "https://github.com/str4d/ire"
repository = "https://github.com/str4d/ire"
readme = "README.md"
categories = ["cryptography"]
keywords = ["i2p", "net", "network", "privacy", "security"]

[dependencies]
aes = "0.2"
arrayref = "0.3"
block-modes = "0.1"
byteorder = "1.2"
bytes = "0.4"
clap = { version = "2.32", optional = true }
cookie-factory = "0.2"
data-encoding = "2.1"
env_logger = { version = "0.5", optional = true }
flate2 = "1.0"
futures = "0.1"
i2p_snow = "0.3.1"
itertools = "0.7"
lazy_static = "1.0"
log = "0.4"
nom = "4.0"
num-bigint = { version = "0.2", features = ["rand"] }
num-traits = "0.2"
rand = "0.5"
ring = "0.13"
sha1 = "0.6"
sha2 = "0.7"
signatory = { version = "0.9.0-alpha3", features = ["ecdsa", "ed25519"] }
signatory-dalek = "0.9.0-alpha3"
signatory-ring = "0.9.0-alpha3"
siphasher = "0.2"
tokio = { version = "0.1", optional = true }
tokio-codec = "0.1"
tokio-executor = "0.1"
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-timer = "0.2"
untrusted = "0.6"

[dev-dependencies]
pretty_assertions = "0.5"
tempfile = "3"

[patch.crates-io]
ring = { git = "https://github.com/str4d/ring.git", branch = "i2p-rsa-raw" }

[features]
cli = ["clap", "env_logger", "tokio"]
nightly = []

[[bin]]
name = "ire"
required-features = ["cli"]
